### ISSUE TITLE
This generator likely doesn't work for Namecoin

### ISSUE THREAD

**Issue by MichaelMure** [kargakis/cryptowallet#2]
https://github.com/kargakis/cryptowallet/blob/da59d728c37a3f750a077ffb889caf67adf9066d/main.go#L40

`netParams.PrivateKeyID = netParams.PubKeyHashAddrID + 128`

This is not always true. In particular, it's not true for Namecoin, so this generator likely produce keys that cannot be imported on a Namecoin software wallet.

Note that I didn't verify my claim.

**Comment by MichaelMure** [comment]
The private key prefix for Namecoin is 0x80 (same as Bitcoin). You can find a good list of those values here: https://github.com/MichaelMure/WalletGenerator.net/blob/master/src/janin.currency.js#L77

**Comment by kargakis** [comment]
Thanks a lot for pointing this out!
